#!/usr/bin/env python3
"""Generate ThesisFrame Technical Audit Report PDF."""

import os
import sys
import hashlib
import subprocess
import tempfile
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, CondPageBreak
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f5f6f6')
SECTION_BG    = colors.HexColor('#ebeced')
CARD_BG       = colors.HexColor('#e7eaeb')
TABLE_STRIPE  = colors.HexColor('#eceff0')
HEADER_FILL   = colors.HexColor('#536873')
COVER_BLOCK   = colors.HexColor('#4d626c')
BORDER        = colors.HexColor('#b1c4cd')
ICON          = colors.HexColor('#51849e')
ACCENT        = colors.HexColor('#378bb5')
ACCENT_2      = colors.HexColor('#a44252')
TEXT_PRIMARY   = colors.HexColor('#1d1f20')
TEXT_MUTED     = colors.HexColor('#707679')
SEM_SUCCESS   = colors.HexColor('#4b825e')
SEM_WARNING   = colors.HexColor('#9f844e')
SEM_ERROR     = colors.HexColor('#994740')
SEM_INFO      = colors.HexColor('#4d7195')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ━━ Font Setup ━━
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# ━━ Paths ━━
OUTPUT_PDF = '/home/z/my-project/audit-thesisframe.pdf'
BODY_PDF = '/tmp/audit-thesisframe-body.pdf'
COVER_HTML = '/tmp/audit-thesisframe-cover.html'
COVER_PDF = '/tmp/audit-thesisframe-cover.pdf'
PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'

# ━━ Page geometry ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 0.85 * inch
RIGHT_MARGIN = 0.85 * inch
TOP_MARGIN = 0.75 * inch
BOTTOM_MARGIN = 0.75 * inch
AVAILABLE_W = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Styles ━━
styles = getSampleStyleSheet()

s_h1 = ParagraphStyle(
    'AuditH1', fontName='FreeSerif-Bold', fontSize=18, leading=24,
    textColor=HEADER_FILL, spaceBefore=18, spaceAfter=10, alignment=TA_LEFT
)
s_h2 = ParagraphStyle(
    'AuditH2', fontName='FreeSerif-Bold', fontSize=14, leading=19,
    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8, alignment=TA_LEFT
)
s_h3 = ParagraphStyle(
    'AuditH3', fontName='FreeSerif-Bold', fontSize=11.5, leading=16,
    textColor=ICON, spaceBefore=10, spaceAfter=6, alignment=TA_LEFT
)
s_body = ParagraphStyle(
    'AuditBody', fontName='FreeSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=6, alignment=TA_JUSTIFY
)
s_body_left = ParagraphStyle(
    'AuditBodyLeft', fontName='FreeSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=6, alignment=TA_LEFT
)
s_bullet = ParagraphStyle(
    'AuditBullet', fontName='FreeSerif', fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, spaceBefore=2, spaceAfter=2,
    leftIndent=18, bulletIndent=6, alignment=TA_LEFT
)
s_th = ParagraphStyle(
    'TableHeader', fontName='FreeSerif-Bold', fontSize=9, leading=12,
    textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER
)

class CellStyle:
    """Create cell styles on-the-fly with minimal font size."""
    _cache = {}
    @classmethod
    def get(cls, name='tc', size=8.5, align=TA_LEFT):
        key = (name, size, align)
        if key not in cls._cache:
            cls._cache[key] = ParagraphStyle(
                f'Cell_{name}_{size}_{align}',
                fontName='FreeSerif', fontSize=size, leading=size+3.5,
                textColor=TEXT_PRIMARY, alignment=align
            )
        return cls._cache[key]

tc = CellStyle.get

def status_color(status):
    """Return a colored Paragraph for status badges."""
    mapping = {
        'COMPLETE': (SEM_SUCCESS, 'Complet'),
        'PARTIAL': (SEM_WARNING, 'Partiel'),
        'STUB': (SEM_INFO, 'Embout'),
        'BROKEN': (SEM_ERROR, 'Cassee'),
        'OUI': (SEM_SUCCESS, 'Oui'),
        'NON': (SEM_ERROR, 'Non'),
    }
    col, label = mapping.get(status, (TEXT_MUTED, status))
    s = ParagraphStyle('st_' + status, fontName='FreeSerif-Bold', fontSize=8, leading=10,
                       textColor=col, alignment=TA_CENTER)
    return Paragraph(label, s)

# ━━ TOC DocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def add_heading(text, style, level=0):
    key = f'h_{hashlib.md5(text.encode()).hexdigest()[:8]}'
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def make_table(header, rows, col_widths=None):
    """Build a styled table with header and rows. All cells as Paragraphs."""
    data = [[Paragraph(f'<b>{h}</b>', s_th) for h in header]]
    for row in rows:
        data.append([Paragraph(str(c), tc()) if not isinstance(c, Paragraph) else c for c in row])
    if col_widths is None:
        n = len(header)
        col_widths = [AVAILABLE_W / n] * n
    else:
        total = sum(col_widths)
        if total < AVAILABLE_W * 0.85:
            scale = (AVAILABLE_W * 0.95) / total
            col_widths = [w * scale for w in col_widths]
    tbl = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 0 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl

def sp(pts=12):
    return Spacer(1, pts)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# COVER HTML (Template 01: HUD Data Terminal)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
def generate_cover_html():
    return f'''<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;900&display=swap" rel="stylesheet">
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ width: 794px; height: 1123px; background: #fff; overflow: hidden; font-family: 'Inter', sans-serif; }}
  .cover-page {{ position: relative; width: 794px; height: 1123px; border: none; outline: none; box-shadow: none; }}

  /* Layer 1: Background grid */
  .cover-layer-1 {{ position: absolute; inset: 0; overflow: hidden; z-index: 1; }}
  .grid-bg {{
    position: absolute; inset: 0;
    background-image:
      linear-gradient(rgba(83,104,115,0.03) 1px, transparent 1px),
      linear-gradient(90deg, rgba(83,104,115,0.03) 1px, transparent 1px);
    background-size: 50px 50px;
  }}

  /* Layer 2: Structure */
  .cover-layer-2 {{ position: absolute; inset: 0; z-index: 2; }}
  .anchor-line {{
    position: absolute;
    left: 95px;  /* 0.12 * 794 */
    top: 112px;  /* 0.1 * 1123 */
    bottom: 101px; /* 0.9 * 1123 */
    width: 6pt;
    background: #536873;
  }}

  /* Layer 3: Content */
  .cover-layer-3 {{ position: absolute; inset: 0; z-index: 3; }}
  .x-content {{ position: absolute; left: 125px; }}
  .kicker {{ top: 168px; font-size: 16pt; font-weight: 400; letter-spacing: 3pt; color: rgba(29,31,32,0.6); text-transform: uppercase; }}
  .hero-title {{ top: 337px; font-size: 55pt; font-weight: 900; color: #1d1f20; line-height: 1.12; max-width: 540px; }}
  .summary {{ top: 560px; font-size: 16pt; font-weight: 400; color: rgba(29,31,32,0.85); line-height: 1.6; max-width: 460px; }}
  .meta {{ top: 730px; font-size: 18pt; font-weight: 400; color: rgba(29,31,32,0.70); line-height: 1.4; }}
  .footer {{ position: absolute; bottom: 40px; right: 50px; font-size: 14pt; font-weight: 400; letter-spacing: 2pt; color: rgba(29,31,32,0.4); text-transform: uppercase; }}
</style>
</head>
<body>
<div class="cover-page">
  <div class="cover-layer-1"><div class="grid-bg"></div></div>
  <div class="cover-layer-2"><div class="anchor-line"></div></div>
  <div class="cover-layer-3">
    <div class="x-content kicker">Audit technique</div>
    <div class="x-content hero-title">THESISFRAME</div>
    <div class="x-content summary">Application d'assistance a la redaction de these.<br>Rapport d'audit exhaustif couvrant 41 fonctionnalites, 78 routes API et l'ensemble des composants front-end.</div>
    <div class="x-content meta">Juin 2025<br>Version 1.0</div>
  </div>
  <div class="footer">Document confidentiel</div>
</div>
</body>
</html>'''

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# BODY CONTENT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
def build_body():
    story = []

    # ── TOC ──
    toc = TableOfContents()
    toc.levelStyles = [
        ParagraphStyle('TOC1', fontName='FreeSerif-Bold', fontSize=12, leading=20, leftIndent=20, textColor=TEXT_PRIMARY),
        ParagraphStyle('TOC2', fontName='FreeSerif', fontSize=10.5, leading=18, leftIndent=40, textColor=TEXT_MUTED),
    ]
    story.append(Paragraph('<b>Table des matieres</b>', ParagraphStyle('TOCTitle', fontName='FreeSerif-Bold', fontSize=20, leading=28, textColor=HEADER_FILL, spaceAfter=18)))
    story.append(toc)
    story.append(PageBreak())

    # ═══════════════════════════════════════
    # CHAPITRE 1 : RESUME EXECUTIF
    # ═══════════════════════════════════════
    story.append(add_heading('<b>1. Resume executif</b>', s_h1, 0))
    story.append(sp(8))

    story.append(Paragraph(
        'Cet audit technique couvre l\'application ThesisFrame, un outil d\'assistance a la redaction de these destine aux doctorants. '
        'L\'evaluation porte sur 41 fonctionnalites identifiees, 78 routes API, 30+ composants front-end, et les donnees structurees associees. '
        'Le scenario de test retenu porte sur le sujet : <b>Impact du changement climatique sur la biodiversite urbaine</b>, en mode mixte '
        '(parties et chapitres).', s_body))
    story.append(sp(6))

    # Summary stats table
    summary_header = ['Indicateur', 'Valeur']
    summary_rows = [
        ['Fonctionnalites testees', '41'],
        ['Fonctionnalites completes', '27 (66 %)'],
        ['Fonctionnalites partielles', '8 (20 %)'],
        ['Fonctionnalites cassees', '6 (14 %)'],
        ['Composants orphelins', '6'],
        ['Routes API orphelines', '15'],
        ['Fichiers de donnees orphelins', '1'],
        ['Fichiers avec TODO/FIXME', '8'],
    ]
    cw = [AVAILABLE_W * 0.55, AVAILABLE_W * 0.45]
    story.append(sp(12))
    story.append(make_table(summary_header, summary_rows, cw))
    story.append(sp(12))

    story.append(add_heading('<b>1.1 Cinq constats principaux</b>', s_h2, 1))
    top5 = [
        'La route POST /api/thesis/chapters ignore silencieusement le champ content (ligne 64 du routeur), '
        'rendant impossible la creation d\'un chapitre avec du contenu en une seule operation.',
        'Les exports Office (DOCX/PPTX) sont completement inoperants en raison d\'une dependance binaire manquante (officecli).',
        'Les 4 routes Academy DB (Anna\'s Archive, LibGen IM, LibGuides, Welib) sont toutes cassees : '
        'elles tentent de parser du HTML en JSON.',
        'La base de connaissances est riche (51 ressources, 52 BookSkills, architecture 3 couches) et constitue un veritable atout differentiel.',
        'Le Directeur IA respecte strictement la doctrine critique-only : aucune generation de texte de these, '
        '7 modes specialises, et un systeme prompt robuste.',
    ]
    for i, item in enumerate(top5, 1):
        story.append(Paragraph(f'<b>{i}.</b> {item}', s_bullet))

    # ═══════════════════════════════════════
    # CHAPITRE 2 : METHODOLOGIE
    # ═══════════════════════════════════════
    story.append(sp(18))
    story.append(add_heading('<b>2. Methodologie</b>', s_h1, 0))
    story.append(sp(8))

    story.append(add_heading('<b>2.1 Scenario de test</b>', s_h2, 1))
    story.append(Paragraph(
        'Un scenario aleatoire a ete utilise pour l\'ensemble des tests :', s_body))
    scenario_header = ['Parametre', 'Valeur']
    scenario_rows = [
        ['Sujet', 'Impact du changement climatique sur la biodiversite urbaine'],
        ['Type de these', 'Mixte (quantitatif + ethnographique)'],
        ['Mode de structure', 'Parties et chapitres'],
        ['Nombre de chapitres par defaut', '6 (Introduction a Conclusion)'],
    ]
    story.append(sp(8))
    story.append(make_table(scenario_header, scenario_rows, cw))
    story.append(sp(12))

    story.append(add_heading('<b>2.2 Environnement de test</b>', s_h2, 1))
    env_rows = [
        ['Application', 'ThesisFrame (Next.js 14, Prisma ORM, TipTap editor)'],
        ['Base de donnees', 'SQLite via Prisma'],
        ['URL de test', 'http://localhost:3000'],
        ['Navigateur', 'Chromium headless via Playwright (agent-browser)'],
        ['Outils API', 'curl en ligne de commande'],
        ['Modules de test', 'A1 (inventaire), A2-part1 a A2-part5 (tests E2E, API, edge cases)'],
    ]
    story.append(make_table(['Element', 'Detail'], env_rows, cw))
    story.append(sp(12))

    # ═══════════════════════════════════════
    # CHAPITRE 3 : INVENTAIRE DES FONCTIONNALITES
    # ═══════════════════════════════════════
    story.append(sp(18))
    story.append(add_heading('<b>3. Inventaire des fonctionnalites</b>', s_h1, 0))
    story.append(sp(8))
    story.append(Paragraph(
        'Le tableau ci-dessous presente les 41 fonctionnalites identifiees lors de l\'audit (tache A1), '
        'avec leur statut de maturite et le resultat des tests. Les composants, routes et fichiers orphelins sont listes separement.', s_body))
    story.append(sp(12))

    # 41 features table
    features = [
        ('F01', 'Editeur TipTap (texte riche)', 'COMPLETE', 'Oui', ''),
        ('F02', 'Gestion des chapitres (CRUD)', 'COMPLETE', 'Oui', ''),
        ('F03', 'Gestion des parties', 'COMPLETE', 'Oui', ''),
        ('F04', 'Bascule mode chapitres/parties', 'PARTIAL', 'Oui', 'Label toujours 